"""Delivery of codes and notices.

Off the request path deliberately. An SMTP server that takes eight seconds must
not be eight seconds of a sign-in, and an SMS gateway that is down must not be a
500 on `/auth/login`.

Every task here is **idempotent in effect**: delivery is at-least-once, so a
retry may send a second copy of a code. That is acceptable - both copies verify
against the same stored digest, and the first one used consumes it. What is not
acceptable is a task that *generates* a new code on retry, which would invalidate
the one already in the user's hand. Codes are therefore generated by the caller
and passed in.

The transport is deliberately a seam. `_deliver` is the only function that talks
to the outside world, so swapping SES/Twilio/an internal gateway is one edit and
the retry, timeout and logging behaviour is unchanged.
"""

from __future__ import annotations

from typing import Any

from celery import shared_task
from celery.exceptions import SoftTimeLimitExceeded

from cmp.core.config import settings
from cmp.core.logging import get_logger
from cmp.infrastructure.email import build_email_transport
from cmp.infrastructure.email.transport import obscure
from cmp.infrastructure.sms import build_sms_transport

log = get_logger("cmp.tasks.notifications")

# Retry on transport failure with exponential backoff and jitter. Without jitter,
# a gateway outage produces a synchronised retry storm the moment it recovers.
RETRY_KW: dict[str, Any] = {
    "autoretry_for": (ConnectionError, TimeoutError, OSError),
    "retry_backoff": 5,
    "retry_backoff_max": 300,
    "retry_jitter": True,
    "max_retries": 5,
    "acks_late": True,
}


def _deliver(*, channel: str, to: str, subject: str, body: str) -> dict[str, Any]:
    """Hand a message to the transport this environment is configured for.

    The transport itself lives in `cmp.infrastructure` — swapping the console
    outbox for SMTP is a setting, not an edit here. What stays with the task is
    the retry policy, because Celery owns retries and two policies disagreeing
    about how many attempts is too many is worse than one.

    Failure propagates. A transport that swallowed an error and returned quietly
    would turn a retryable outage into silent data loss.
    """
    if channel == "sms":
        return dict(build_sms_transport().send(to=to, body=body))
    return dict(build_email_transport().send(to=to, subject=subject, body=body))


@shared_task(name="cmp.notifications.send_mfa_code", **RETRY_KW)
def send_mfa_code(user_uuid: str, email: str, code: str) -> dict[str, Any]:
    return _deliver(
        channel="email",
        to=email,
        subject="Your verification code",
        body=(
            f"Your verification code is {code}. "
            f"It expires in {settings.mfa_ttl_s // 60} minutes. "
            "If you did not try to sign in, tell the Privacy Office."
        ),
    )


@shared_task(name="cmp.notifications.send_login_code", **RETRY_KW)
def send_login_code(user_uuid: str, contact: str, code: str) -> dict[str, Any]:
    channel = "email" if "@" in contact else "sms"
    return _deliver(
        channel=channel,
        to=contact,
        subject="Your sign-in code",
        body=(
            f"Your sign-in code is {code}. "
            f"It expires in {settings.otp_ttl_s // 60} minutes."
        ),
    )


@shared_task(name="cmp.notifications.send_consent_code", **RETRY_KW)
def send_consent_code(contact: str, code: str) -> dict[str, Any]:
    channel = "email" if "@" in contact else "sms"
    return _deliver(
        channel=channel,
        to=contact,
        subject="Confirm your contact details",
        body=(
            f"Your confirmation code is {code}. "
            f"It expires in {settings.otp_ttl_s // 60} minutes."
        ),
    )


@shared_task(name="cmp.notifications.send_password_reset", **RETRY_KW)
def send_password_reset(user_uuid: str, email: str, code: str) -> dict[str, Any]:
    return _deliver(
        channel="email",
        to=email,
        subject="Reset your password",
        body=f"Your password reset code is {code}. It expires in 15 minutes.",
    )


@shared_task(name="cmp.notifications.send_consent_receipt", **RETRY_KW)
def send_consent_receipt(contact: str, consent_uuid: str, project_name: str) -> dict[str, Any]:
    """A receipt is not a courtesy; it is the subject's copy of the evidence.

    It carries the artefact reference so she can quote it when exercising a
    right, and it is what makes a later "I never consented to that" checkable by
    both sides.
    """
    return _deliver(
        channel="email" if "@" in contact else "sms",
        to=contact,
        subject=f"Your consent record for {project_name}",
        body=(
            f"Your consent has been recorded. Reference: {consent_uuid}. "
            "You can review or withdraw it at any time from your account."
        ),
    )


@shared_task(name="cmp.notifications.send_withdrawal_confirmation", **RETRY_KW)
def send_withdrawal_confirmation(
    contact: str, consent_uuid: str, stopped: list[str], continuing: list[str]
) -> dict[str, Any]:
    """Withdrawal confirmations state what continues, not only what stops.

    Data already collected is not reached by a withdrawal, and a confirmation
    that implies otherwise sets an expectation the platform cannot meet.
    """
    lines = [f"Your withdrawal has been recorded. Reference: {consent_uuid}."]
    if stopped:
        lines.append("Stopped: " + ", ".join(stopped) + ".")
    if continuing:
        lines.append(
            "Continuing under a separate lawful basis: " + ", ".join(continuing) + "."
        )
    lines.append(
        "Data already collected is not deleted by this withdrawal. "
        "To ask for erasure, use the rights request form."
    )
    return _deliver(
        channel="email" if "@" in contact else "sms",
        to=contact,
        subject="Your withdrawal has been recorded",
        body=" ".join(lines),
    )


@shared_task(
    name="cmp.notifications.notify_project_event",
    bind=True,
    **RETRY_KW,
)
def notify_project_event(
    self: Any, recipients: list[str], subject: str, body: str
) -> dict[str, Any]:
    """Fan-out to staff for a workflow event - a queue item awaiting their action.

    Partial failure is reported rather than retried wholesale: retrying the whole
    batch would re-deliver to everyone who already received it.
    """
    delivered, failed = 0, []
    try:
        for address in recipients:
            try:
                _deliver(channel="email", to=address, subject=subject, body=body)
                delivered += 1
            except (ConnectionError, TimeoutError, OSError) as exc:
                failed.append({"to": obscure(address), "error": type(exc).__name__})
    except SoftTimeLimitExceeded:
        log.warning("notification.batch_timed_out", delivered=delivered,
                    remaining=len(recipients) - delivered)
        raise

    if failed:
        log.warning("notification.batch_partial", delivered=delivered, failed=len(failed))
    return {"delivered": delivered, "failed": failed}
